//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemicalDataSourcesTestApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChemicalDataSourcesTestApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetaldehyde	75-07-0	10 ppm	200 ppm	1000 PPM	
        ///Acetic Acid 	64-19-7	5 ppm	35 ppm	250 ppm 	
        ///Acetic Anhydride	108-24-7	0.5 ppm	15 ppm 	15 ppm 	
        ///Acrolein	107-02-8	0.05 ppm	0.15 ppm	1.5 ppm	
        ///Acrylic Acid 	79-10-7	1 ppm	50 ppm	250 ppm	
        ///Acrylonitrile 	107-13-1	10 ppm	35 ppm	75 ppm 	
        ///Allyl Chloride	107-05-1	3 ppm	40 ppm	300 ppm 	
        ///Ammonia	7664-41-7	25 ppm	150 ppm	1000 ppm 	
        ///Arsine 	7784-42-1	NA†	0.5 ppm	1.5 ppm	
        ///Benzene	71-43-2	50 ppm	150 ppm 	1500 ppm	
        ///&quot;Benzene, ethylenated, by-products from (Dowtherm Q)  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2015_ERPG_Levels {
            get {
                return ResourceManager.GetString("_2015_ERPG_Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001-001-00-9	hydrogen	215-605-7	1333-74-0	Flam. Gas 1Press. Gas	H220	GHS02GHS04Dgr	H220	EUH001		U	CLP00
        ///001-002-00-4	aluminium lithium hydride	240-877-9	16853-85-3	Water-react. 1Skin Corr. 1A	H260H314	GHS02GHS05Dgr	H260H314				CLP00/ATP01
        ///001-003-00-X	sodium hydride	231-587-3	7646-69-7	Water-react. 1	H260	GHS02Dgr	H260				CLP00
        ///001-004-00-5	calcium hydride	232-189-2	7789-78-8	Water-react. 1	H260	GHS02Dgr	H260				CLP00
        ///003-001-00-4	lithium	231-102-5	7439-93-2	Water-react. 1Skin Corr. 1B	H260H314	GHS02GHS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string annex_vi_clp_table_en {
            get {
                return ResourceManager.GetString("annex_vi_clp_table_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetaldehyd	1084805	75-07-0	1541	1	WGK 1: low hazard to waters
        ///Acetamid	1084806	60-35-5	1541	1	WGK 1: low hazard to waters
        ///Acetanhydrid	1084807	108-24-7	1541	1	WGK 1: low hazard to waters
        ///Acetessigsureethylester	1084808	141-97-9	1541	1	WGK 1: low hazard to waters
        ///Acetessigsuremethylester	1084809	105-45-3	1541	1	WGK 1: low hazard to waters
        ///Aceton	1084810	67-64-1	1541	1	WGK 1: low hazard to waters
        ///Acetoncyanhydrin	1084811	75-86-5	1541	3	WGK 3: severe hazard to waters
        ///Acetonitril	1084812	75-05-8	1541	2	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DE_Hazardous_Water_AID_1 {
            get {
                return ResourceManager.GetString("DE_Hazardous_Water_AID_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	001-001-00-9	215-605-7	1333-74-0	hydrogen	53968	http://echa.europa.eu/information-on-chemicals/cl-inventory-database/-/discli/details/53968
        ///2	001-002-00-4	240-877-9	16853-85-3	aluminium lithium hydride	110445	http://echa.europa.eu/information-on-chemicals/cl-inventory-database/-/discli/details/110445
        ///3	001-003-00-X	231-587-3	7646-69-7	sodium hydride	25621	http://echa.europa.eu/information-on-chemicals/cl-inventory-database/-/discli/details/25621
        ///4	001-004-00-5	232-189-2	7789-78-8	calcium hydride	126837 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string europeanChemicalList {
            get {
                return ResourceManager.GetString("europeanChemicalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1237* SEE
        ///0275* 50-00-0
        ///0695* 50-00-0
        ///0894* 50-01-1
        ///0689* 50-18-0
        ///0501* 50-21-5
        ///0034* 50-29-3
        ///0104* 50-32-8
        ///0892* 50-70-4
        ///0822* 50-78-2
        ///0379* 50-81-7
        ///0865* 50-99-7
        ///1347* 51-03-6
        ///0464* 51-28-5
        ///0314* 51-79-6
        ///0415* 52-51-7
        ///0585* 52-68-6
        ///0431* 53-70-3
        ///0519* 54-11-5
        ///1258* 54-85-3
        ///0655* 55-38-9
        ///1528* 55-55-0
        ///0186* 55-63-0
        ///0541* 55-68-5
        ///0024* 56-23-5
        ///1282* 56-35-9
        ///0006* 56-38-2
        ///0385* 56-55-3
        ///0422* 56-72-4
        ///0624* 56-81-5
        ///1439* 56-84-8
        ///0372* 57-06-7
        ///0530* 57-10-3
        ///0568* 57-11-4
        ///0595*  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ICSCnumberByCAS {
            get {
                return ResourceManager.GetString("ICSCnumberByCAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetaldehyde(http://www.cdc.gov/niosh/idlh/75070.html)	&quot;10,000 ppm&quot;	&quot;2,000 ppm&quot;
        ///Acetic acid(http://www.cdc.gov/niosh/idlh/64197.html)	&quot;1,000 ppm&quot;	50 ppm
        ///Acetic anhydride(http://www.cdc.gov/niosh/idlh/108247.html)	&quot;1,000 ppm&quot;	200 ppm
        ///Acetone(http://www.cdc.gov/niosh/idlh/67641.html)	&quot;20,000 ppm&quot;	&quot;2,500 ppm [LEL]&quot;
        ///Acetonitrile(http://www.cdc.gov/niosh/idlh/75058.html)	&quot;4,000 ppm&quot;	500 ppm
        ///Acetylene tetrabromide(http://www.cdc.gov/niosh/idlh/79276.html)	10 ppm	8 ppm
        ///Acrolein(http://www.cdc.gov/niosh/idlh/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string idlh {
            get {
                return ResourceManager.GetString("idlh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abamectin	ABAMECTIN AVERMECTIN B1	71751412	71751-41-2 				313								
        ///Acenaphthene	ACENAPHTHENE	83329	83-32-9 			100									
        ///Acenaphthylene	ACENAPHTHYLENE	208968	208-96-8 			&quot;5,000&quot;									
        ///Acephate	ACEPHATE	30560191	30560-19-1 				313								
        ///Acetaldehyde	ACETALDEHYDE	75070	75-07-0 			&quot;1,000&quot;	313	U001	&quot;10,000&quot;						
        ///&quot;Acetaldehyde, trichloro-&quot;	&quot;ACETALDEHYDE, TRICHLORO-&quot;	75876	75-87-6 			&quot;5,000&quot;		U034							
        ///Acetamide	ACETAMIDE	60355	60-35-5 			100	313								
        ///Acetic acid	ACETICACID	64197	64-19-7 		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string list_of_lists {
            get {
                return ResourceManager.GetString("list_of_lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nfpa_diamond {
            get {
                object obj = ResourceManager.GetObject("nfpa_diamond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electron	e-	N/A
        ///Iron(2) oxide anion	FeO-	N/A
        ///AsF3..Cl anion	AsClF3-	N/A
        ///AgH2-	H2Ag-	N/A
        ///HAg(H2)	H3Ag	N/A
        ///AgNO+	AgNO+	N/A
        ///AgNO	AgNO	N/A
        ///AgNO-	AgNO-	N/A
        ///AgOO-	AgO2-	N/A
        ///AgAgH	HAg2	N/A
        ///AgAgH-	HAg2-	N/A
        ///AgOAg	Ag2O	N/A
        ///Ag4	Ag4	N/A
        ///Ag5	Ag5	N/A
        ///Ag8	Ag8	N/A
        ///HAlClBr	HAlBrCl	N/A
        ///AlCl2Br	AlBrCl2	N/A
        ///HAlFBr	HAlBrF	N/A
        ///AlF2Br	AlBrF2	N/A
        ///Br(cyc-AlO2)	AlBrO2	N/A
        ///BrAlO2	AlBrO2	N/A
        ///BrAl(O2)2	AlBrO4	N/A
        ///AlClBr2	AlBr2Cl	N/A
        ///AlFBr2	AlBr2F	N/A
        ///HAlBr2	HAlBr2	N/A
        ///HAlFCl	HAlClF	N/A
        ///AlF2Cl	AlClF2	N/A
        ///AlH2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string species {
            get {
                return ResourceManager.GetString("species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 71751-41-2	Abamectin [Avermectin B1]	1.0		
        ///30560-19-1	&quot;Acephate (Acetylphosphoramidothioic acid O,S-dimethyl ester)&quot;	1.0		
        ///75-07-0	Acetaldehyde	0.1		
        ///60-35-5	Acetamide	0.1		
        ///75-05-8	Acetonitrile	1.0		
        ///98-86-2	Acetophenone	1.0		
        ///53-96-3	2-Acetylaminofluorene	0.1		
        ///62476-59-9	&quot;Acifluorfen, sodium salt [5-(2-Chloro-4-(trifluoromethyl)phenoxy)-2-nitrobenzoic acid, sodium salt]&quot;	1.0		
        ///107-02-8	Acrolein	1.0		
        ///79-06-1	Acrylamide	0.1		
        ///79-10-7	Acrylic acid	1.0		
        ///107-13-1	Acrylonitrile	0.1		
        ///15972-60-8	A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tri_chemical_list_for_ry15_11_5_2015_1 {
            get {
                return ResourceManager.GetString("tri_chemical_list_for_ry15_11_5_2015_1", resourceCulture);
            }
        }
    }
}
