//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/hierarchy_data")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/hierarchy_data", IsNullable=false)]
public partial class Hierarchies {
    
    private Hierarchy[] hierarchyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Hierarchy")]
    public Hierarchy[] Hierarchy {
        get {
            return this.hierarchyField;
        }
        set {
            this.hierarchyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/hierarchy_data")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/hierarchy_data", IsNullable=false)]
public partial class Hierarchy {
    
    private string sourceNameField;
    
    private string sourceIDField;
    
    private string rootIDField;
    
    private int hIDField;
    
    private bool hIDFieldSpecified;
    
    private Information informationField;
    
    private Node[] nodeField;
    
    private Flags flagsField;
    
    /// <remarks/>
    public string SourceName {
        get {
            return this.sourceNameField;
        }
        set {
            this.sourceNameField = value;
        }
    }
    
    /// <remarks/>
    public string SourceID {
        get {
            return this.sourceIDField;
        }
        set {
            this.sourceIDField = value;
        }
    }
    
    /// <remarks/>
    public string RootID {
        get {
            return this.rootIDField;
        }
        set {
            this.rootIDField = value;
        }
    }
    
    /// <remarks/>
    public int HID {
        get {
            return this.hIDField;
        }
        set {
            this.hIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HIDSpecified {
        get {
            return this.hIDFieldSpecified;
        }
        set {
            this.hIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public Information Information {
        get {
            return this.informationField;
        }
        set {
            this.informationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Node")]
    public Node[] Node {
        get {
            return this.nodeField;
        }
        set {
            this.nodeField = value;
        }
    }
    
    /// <remarks/>
    public Flags Flags {
        get {
            return this.flagsField;
        }
        set {
            this.flagsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/hierarchy_data")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/hierarchy_data", IsNullable=false)]
public partial class Information {
    
    private string nameField;
    
    private string[] descriptionField;
    
    private string[] commentsField;
    
    private string uRLField;
    
    private int hNIDField;
    
    private bool hNIDFieldSpecified;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description")]
    public string[] Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Comments")]
    public string[] Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    public string URL {
        get {
            return this.uRLField;
        }
        set {
            this.uRLField = value;
        }
    }
    
    /// <remarks/>
    public int HNID {
        get {
            return this.hNIDField;
        }
        set {
            this.hNIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HNIDSpecified {
        get {
            return this.hNIDFieldSpecified;
        }
        set {
            this.hNIDFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/hierarchy_data")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/hierarchy_data", IsNullable=false)]
public partial class Node {
    
    private string nodeIDField;
    
    private string[] parentIDField;
    
    private string[][] pathToRootField;
    
    private Information informationField;
    
    private XRefs xRefsField;
    
    /// <remarks/>
    public string NodeID {
        get {
            return this.nodeIDField;
        }
        set {
            this.nodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ParentID")]
    public string[] ParentID {
        get {
            return this.parentIDField;
        }
        set {
            this.parentIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("AncestorID", typeof(string), IsNullable=false)]
    public string[][] PathToRoot {
        get {
            return this.pathToRootField;
        }
        set {
            this.pathToRootField = value;
        }
    }
    
    /// <remarks/>
    public Information Information {
        get {
            return this.informationField;
        }
        set {
            this.informationField = value;
        }
    }
    
    /// <remarks/>
    public XRefs XRefs {
        get {
            return this.xRefsField;
        }
        set {
            this.xRefsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/hierarchy_data")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/hierarchy_data", IsNullable=false)]
public partial class XRefs {
    
    private XRefsXRef_Source[] xRef_SourceField;
    
    private string[] xRef_PubChemSIDField;
    
    private string[] xRef_PubChemCIDField;
    
    private string[] xRef_PubChemAIDField;
    
    private string[] xRef_SynonymField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("XRef_Source")]
    public XRefsXRef_Source[] XRef_Source {
        get {
            return this.xRef_SourceField;
        }
        set {
            this.xRef_SourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("XRef_PubChemSID", DataType="integer")]
    public string[] XRef_PubChemSID {
        get {
            return this.xRef_PubChemSIDField;
        }
        set {
            this.xRef_PubChemSIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("XRef_PubChemCID", DataType="integer")]
    public string[] XRef_PubChemCID {
        get {
            return this.xRef_PubChemCIDField;
        }
        set {
            this.xRef_PubChemCIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("XRef_PubChemAID", DataType="integer")]
    public string[] XRef_PubChemAID {
        get {
            return this.xRef_PubChemAIDField;
        }
        set {
            this.xRef_PubChemAIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("XRef_Synonym")]
    public string[] XRef_Synonym {
        get {
            return this.xRef_SynonymField;
        }
        set {
            this.xRef_SynonymField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/hierarchy_data")]
public partial class XRefsXRef_Source {
    
    private string xRef_SourceNameField;
    
    private string xRef_SourceIDField;
    
    /// <remarks/>
    public string XRef_SourceName {
        get {
            return this.xRef_SourceNameField;
        }
        set {
            this.xRef_SourceNameField = value;
        }
    }
    
    /// <remarks/>
    public string XRef_SourceID {
        get {
            return this.xRef_SourceIDField;
        }
        set {
            this.xRef_SourceIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/hierarchy_data")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/hierarchy_data", IsNullable=false)]
public partial class Flags {
    
    private bool autoMatchSourceToSIDField;
    
    private bool autoMatchSourceToSIDFieldSpecified;
    
    private bool autoMatchSIDToCIDField;
    
    private bool autoMatchSIDToCIDFieldSpecified;
    
    private bool autoConstructPathsField;
    
    private bool autoConstructPathsFieldSpecified;
    
    private bool autoMatchMeSHToSCIDField;
    
    private bool autoMatchMeSHToSCIDFieldSpecified;
    
    /// <remarks/>
    public bool AutoMatchSourceToSID {
        get {
            return this.autoMatchSourceToSIDField;
        }
        set {
            this.autoMatchSourceToSIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AutoMatchSourceToSIDSpecified {
        get {
            return this.autoMatchSourceToSIDFieldSpecified;
        }
        set {
            this.autoMatchSourceToSIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool AutoMatchSIDToCID {
        get {
            return this.autoMatchSIDToCIDField;
        }
        set {
            this.autoMatchSIDToCIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AutoMatchSIDToCIDSpecified {
        get {
            return this.autoMatchSIDToCIDFieldSpecified;
        }
        set {
            this.autoMatchSIDToCIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool AutoConstructPaths {
        get {
            return this.autoConstructPathsField;
        }
        set {
            this.autoConstructPathsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AutoConstructPathsSpecified {
        get {
            return this.autoConstructPathsFieldSpecified;
        }
        set {
            this.autoConstructPathsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool AutoMatchMeSHToSCID {
        get {
            return this.autoMatchMeSHToSCIDField;
        }
        set {
            this.autoMatchMeSHToSCIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AutoMatchMeSHToSCIDSpecified {
        get {
            return this.autoMatchMeSHToSCIDFieldSpecified;
        }
        set {
            this.autoMatchMeSHToSCIDFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/hierarchy_data")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/hierarchy_data", IsNullable=false)]
public partial class PathToRoot {
    
    private string[] ancestorIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AncestorID")]
    public string[] AncestorID {
        get {
            return this.ancestorIDField;
        }
        set {
            this.ancestorIDField = value;
        }
    }
}
