//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest", IsNullable=false)]
public partial class Fault {
    
    private string codeField;
    
    private string messageField;
    
    private string[] detailsField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Details")]
    public string[] Details {
        get {
            return this.detailsField;
        }
        set {
            this.detailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest")]
public partial class DateTime {
    
    private int yearField;
    
    private bool yearFieldSpecified;
    
    private int monthField;
    
    private bool monthFieldSpecified;
    
    private int dayField;
    
    private bool dayFieldSpecified;
    
    private int hourField;
    
    private bool hourFieldSpecified;
    
    private int minuteField;
    
    private bool minuteFieldSpecified;
    
    private int secondField;
    
    private bool secondFieldSpecified;
    
    /// <remarks/>
    public int Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool YearSpecified {
        get {
            return this.yearFieldSpecified;
        }
        set {
            this.yearFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Month {
        get {
            return this.monthField;
        }
        set {
            this.monthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MonthSpecified {
        get {
            return this.monthFieldSpecified;
        }
        set {
            this.monthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DaySpecified {
        get {
            return this.dayFieldSpecified;
        }
        set {
            this.dayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Hour {
        get {
            return this.hourField;
        }
        set {
            this.hourField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HourSpecified {
        get {
            return this.hourFieldSpecified;
        }
        set {
            this.hourFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Minute {
        get {
            return this.minuteField;
        }
        set {
            this.minuteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MinuteSpecified {
        get {
            return this.minuteFieldSpecified;
        }
        set {
            this.minuteFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Second {
        get {
            return this.secondField;
        }
        set {
            this.secondField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SecondSpecified {
        get {
            return this.secondFieldSpecified;
        }
        set {
            this.secondFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest", IsNullable=false)]
public partial class Waiting {
    
    private string listKeyField;
    
    private string messageField;
    
    /// <remarks/>
    public string ListKey {
        get {
            return this.listKeyField;
        }
        set {
            this.listKeyField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest", IsNullable=false)]
public partial class PropertyTable {
    
    private PropertyTableProperties[] propertiesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Properties")]
    public PropertyTableProperties[] Properties {
        get {
            return this.propertiesField;
        }
        set {
            this.propertiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest")]
public partial class PropertyTableProperties {
    
    private int cIDField;
    
    private string molecularFormulaField;
    
    private double molecularWeightField;
    
    private bool molecularWeightFieldSpecified;
    
    private string canonicalSMILESField;
    
    private string isomericSMILESField;
    
    private string inChIField;
    
    private string inChIKeyField;
    
    private string iUPACNameField;
    
    private double xLogPField;
    
    private bool xLogPFieldSpecified;
    
    private double exactMassField;
    
    private bool exactMassFieldSpecified;
    
    private double monoisotopicMassField;
    
    private bool monoisotopicMassFieldSpecified;
    
    private double tPSAField;
    
    private bool tPSAFieldSpecified;
    
    private int complexityField;
    
    private bool complexityFieldSpecified;
    
    private int chargeField;
    
    private bool chargeFieldSpecified;
    
    private int hBondDonorCountField;
    
    private bool hBondDonorCountFieldSpecified;
    
    private int hBondAcceptorCountField;
    
    private bool hBondAcceptorCountFieldSpecified;
    
    private int rotatableBondCountField;
    
    private bool rotatableBondCountFieldSpecified;
    
    private int heavyAtomCountField;
    
    private bool heavyAtomCountFieldSpecified;
    
    private int isotopeAtomCountField;
    
    private bool isotopeAtomCountFieldSpecified;
    
    private int atomStereoCountField;
    
    private bool atomStereoCountFieldSpecified;
    
    private int definedAtomStereoCountField;
    
    private bool definedAtomStereoCountFieldSpecified;
    
    private int undefinedAtomStereoCountField;
    
    private bool undefinedAtomStereoCountFieldSpecified;
    
    private int bondStereoCountField;
    
    private bool bondStereoCountFieldSpecified;
    
    private int definedBondStereoCountField;
    
    private bool definedBondStereoCountFieldSpecified;
    
    private int undefinedBondStereoCountField;
    
    private bool undefinedBondStereoCountFieldSpecified;
    
    private int covalentUnitCountField;
    
    private bool covalentUnitCountFieldSpecified;
    
    private double volume3DField;
    
    private bool volume3DFieldSpecified;
    
    private double xStericQuadrupole3DField;
    
    private bool xStericQuadrupole3DFieldSpecified;
    
    private double yStericQuadrupole3DField;
    
    private bool yStericQuadrupole3DFieldSpecified;
    
    private double zStericQuadrupole3DField;
    
    private bool zStericQuadrupole3DFieldSpecified;
    
    private int featureCount3DField;
    
    private bool featureCount3DFieldSpecified;
    
    private int featureAcceptorCount3DField;
    
    private bool featureAcceptorCount3DFieldSpecified;
    
    private int featureDonorCount3DField;
    
    private bool featureDonorCount3DFieldSpecified;
    
    private int featureAnionCount3DField;
    
    private bool featureAnionCount3DFieldSpecified;
    
    private int featureCationCount3DField;
    
    private bool featureCationCount3DFieldSpecified;
    
    private int featureRingCount3DField;
    
    private bool featureRingCount3DFieldSpecified;
    
    private int featureHydrophobeCount3DField;
    
    private bool featureHydrophobeCount3DFieldSpecified;
    
    private double conformerModelRMSD3DField;
    
    private bool conformerModelRMSD3DFieldSpecified;
    
    private double effectiveRotorCount3DField;
    
    private bool effectiveRotorCount3DFieldSpecified;
    
    private int conformerCount3DField;
    
    private bool conformerCount3DFieldSpecified;
    
    private byte[] fingerprint2DField;
    
    /// <remarks/>
    public int CID {
        get {
            return this.cIDField;
        }
        set {
            this.cIDField = value;
        }
    }
    
    /// <remarks/>
    public string MolecularFormula {
        get {
            return this.molecularFormulaField;
        }
        set {
            this.molecularFormulaField = value;
        }
    }
    
    /// <remarks/>
    public double MolecularWeight {
        get {
            return this.molecularWeightField;
        }
        set {
            this.molecularWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MolecularWeightSpecified {
        get {
            return this.molecularWeightFieldSpecified;
        }
        set {
            this.molecularWeightFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string CanonicalSMILES {
        get {
            return this.canonicalSMILESField;
        }
        set {
            this.canonicalSMILESField = value;
        }
    }
    
    /// <remarks/>
    public string IsomericSMILES {
        get {
            return this.isomericSMILESField;
        }
        set {
            this.isomericSMILESField = value;
        }
    }
    
    /// <remarks/>
    public string InChI {
        get {
            return this.inChIField;
        }
        set {
            this.inChIField = value;
        }
    }
    
    /// <remarks/>
    public string InChIKey {
        get {
            return this.inChIKeyField;
        }
        set {
            this.inChIKeyField = value;
        }
    }
    
    /// <remarks/>
    public string IUPACName {
        get {
            return this.iUPACNameField;
        }
        set {
            this.iUPACNameField = value;
        }
    }
    
    /// <remarks/>
    public double XLogP {
        get {
            return this.xLogPField;
        }
        set {
            this.xLogPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool XLogPSpecified {
        get {
            return this.xLogPFieldSpecified;
        }
        set {
            this.xLogPFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double ExactMass {
        get {
            return this.exactMassField;
        }
        set {
            this.exactMassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExactMassSpecified {
        get {
            return this.exactMassFieldSpecified;
        }
        set {
            this.exactMassFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double MonoisotopicMass {
        get {
            return this.monoisotopicMassField;
        }
        set {
            this.monoisotopicMassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MonoisotopicMassSpecified {
        get {
            return this.monoisotopicMassFieldSpecified;
        }
        set {
            this.monoisotopicMassFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double TPSA {
        get {
            return this.tPSAField;
        }
        set {
            this.tPSAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TPSASpecified {
        get {
            return this.tPSAFieldSpecified;
        }
        set {
            this.tPSAFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Complexity {
        get {
            return this.complexityField;
        }
        set {
            this.complexityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ComplexitySpecified {
        get {
            return this.complexityFieldSpecified;
        }
        set {
            this.complexityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Charge {
        get {
            return this.chargeField;
        }
        set {
            this.chargeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ChargeSpecified {
        get {
            return this.chargeFieldSpecified;
        }
        set {
            this.chargeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int HBondDonorCount {
        get {
            return this.hBondDonorCountField;
        }
        set {
            this.hBondDonorCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HBondDonorCountSpecified {
        get {
            return this.hBondDonorCountFieldSpecified;
        }
        set {
            this.hBondDonorCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int HBondAcceptorCount {
        get {
            return this.hBondAcceptorCountField;
        }
        set {
            this.hBondAcceptorCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HBondAcceptorCountSpecified {
        get {
            return this.hBondAcceptorCountFieldSpecified;
        }
        set {
            this.hBondAcceptorCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int RotatableBondCount {
        get {
            return this.rotatableBondCountField;
        }
        set {
            this.rotatableBondCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RotatableBondCountSpecified {
        get {
            return this.rotatableBondCountFieldSpecified;
        }
        set {
            this.rotatableBondCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int HeavyAtomCount {
        get {
            return this.heavyAtomCountField;
        }
        set {
            this.heavyAtomCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HeavyAtomCountSpecified {
        get {
            return this.heavyAtomCountFieldSpecified;
        }
        set {
            this.heavyAtomCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int IsotopeAtomCount {
        get {
            return this.isotopeAtomCountField;
        }
        set {
            this.isotopeAtomCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsotopeAtomCountSpecified {
        get {
            return this.isotopeAtomCountFieldSpecified;
        }
        set {
            this.isotopeAtomCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int AtomStereoCount {
        get {
            return this.atomStereoCountField;
        }
        set {
            this.atomStereoCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AtomStereoCountSpecified {
        get {
            return this.atomStereoCountFieldSpecified;
        }
        set {
            this.atomStereoCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int DefinedAtomStereoCount {
        get {
            return this.definedAtomStereoCountField;
        }
        set {
            this.definedAtomStereoCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DefinedAtomStereoCountSpecified {
        get {
            return this.definedAtomStereoCountFieldSpecified;
        }
        set {
            this.definedAtomStereoCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int UndefinedAtomStereoCount {
        get {
            return this.undefinedAtomStereoCountField;
        }
        set {
            this.undefinedAtomStereoCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UndefinedAtomStereoCountSpecified {
        get {
            return this.undefinedAtomStereoCountFieldSpecified;
        }
        set {
            this.undefinedAtomStereoCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int BondStereoCount {
        get {
            return this.bondStereoCountField;
        }
        set {
            this.bondStereoCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BondStereoCountSpecified {
        get {
            return this.bondStereoCountFieldSpecified;
        }
        set {
            this.bondStereoCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int DefinedBondStereoCount {
        get {
            return this.definedBondStereoCountField;
        }
        set {
            this.definedBondStereoCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DefinedBondStereoCountSpecified {
        get {
            return this.definedBondStereoCountFieldSpecified;
        }
        set {
            this.definedBondStereoCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int UndefinedBondStereoCount {
        get {
            return this.undefinedBondStereoCountField;
        }
        set {
            this.undefinedBondStereoCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UndefinedBondStereoCountSpecified {
        get {
            return this.undefinedBondStereoCountFieldSpecified;
        }
        set {
            this.undefinedBondStereoCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int CovalentUnitCount {
        get {
            return this.covalentUnitCountField;
        }
        set {
            this.covalentUnitCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CovalentUnitCountSpecified {
        get {
            return this.covalentUnitCountFieldSpecified;
        }
        set {
            this.covalentUnitCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double Volume3D {
        get {
            return this.volume3DField;
        }
        set {
            this.volume3DField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Volume3DSpecified {
        get {
            return this.volume3DFieldSpecified;
        }
        set {
            this.volume3DFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double XStericQuadrupole3D {
        get {
            return this.xStericQuadrupole3DField;
        }
        set {
            this.xStericQuadrupole3DField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool XStericQuadrupole3DSpecified {
        get {
            return this.xStericQuadrupole3DFieldSpecified;
        }
        set {
            this.xStericQuadrupole3DFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double YStericQuadrupole3D {
        get {
            return this.yStericQuadrupole3DField;
        }
        set {
            this.yStericQuadrupole3DField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool YStericQuadrupole3DSpecified {
        get {
            return this.yStericQuadrupole3DFieldSpecified;
        }
        set {
            this.yStericQuadrupole3DFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double ZStericQuadrupole3D {
        get {
            return this.zStericQuadrupole3DField;
        }
        set {
            this.zStericQuadrupole3DField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ZStericQuadrupole3DSpecified {
        get {
            return this.zStericQuadrupole3DFieldSpecified;
        }
        set {
            this.zStericQuadrupole3DFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int FeatureCount3D {
        get {
            return this.featureCount3DField;
        }
        set {
            this.featureCount3DField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FeatureCount3DSpecified {
        get {
            return this.featureCount3DFieldSpecified;
        }
        set {
            this.featureCount3DFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int FeatureAcceptorCount3D {
        get {
            return this.featureAcceptorCount3DField;
        }
        set {
            this.featureAcceptorCount3DField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FeatureAcceptorCount3DSpecified {
        get {
            return this.featureAcceptorCount3DFieldSpecified;
        }
        set {
            this.featureAcceptorCount3DFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int FeatureDonorCount3D {
        get {
            return this.featureDonorCount3DField;
        }
        set {
            this.featureDonorCount3DField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FeatureDonorCount3DSpecified {
        get {
            return this.featureDonorCount3DFieldSpecified;
        }
        set {
            this.featureDonorCount3DFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int FeatureAnionCount3D {
        get {
            return this.featureAnionCount3DField;
        }
        set {
            this.featureAnionCount3DField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FeatureAnionCount3DSpecified {
        get {
            return this.featureAnionCount3DFieldSpecified;
        }
        set {
            this.featureAnionCount3DFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int FeatureCationCount3D {
        get {
            return this.featureCationCount3DField;
        }
        set {
            this.featureCationCount3DField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FeatureCationCount3DSpecified {
        get {
            return this.featureCationCount3DFieldSpecified;
        }
        set {
            this.featureCationCount3DFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int FeatureRingCount3D {
        get {
            return this.featureRingCount3DField;
        }
        set {
            this.featureRingCount3DField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FeatureRingCount3DSpecified {
        get {
            return this.featureRingCount3DFieldSpecified;
        }
        set {
            this.featureRingCount3DFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int FeatureHydrophobeCount3D {
        get {
            return this.featureHydrophobeCount3DField;
        }
        set {
            this.featureHydrophobeCount3DField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FeatureHydrophobeCount3DSpecified {
        get {
            return this.featureHydrophobeCount3DFieldSpecified;
        }
        set {
            this.featureHydrophobeCount3DFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double ConformerModelRMSD3D {
        get {
            return this.conformerModelRMSD3DField;
        }
        set {
            this.conformerModelRMSD3DField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ConformerModelRMSD3DSpecified {
        get {
            return this.conformerModelRMSD3DFieldSpecified;
        }
        set {
            this.conformerModelRMSD3DFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double EffectiveRotorCount3D {
        get {
            return this.effectiveRotorCount3DField;
        }
        set {
            this.effectiveRotorCount3DField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EffectiveRotorCount3DSpecified {
        get {
            return this.effectiveRotorCount3DFieldSpecified;
        }
        set {
            this.effectiveRotorCount3DFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int ConformerCount3D {
        get {
            return this.conformerCount3DField;
        }
        set {
            this.conformerCount3DField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ConformerCount3DSpecified {
        get {
            return this.conformerCount3DFieldSpecified;
        }
        set {
            this.conformerCount3DFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Fingerprint2D {
        get {
            return this.fingerprint2DField;
        }
        set {
            this.fingerprint2DField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest", IsNullable=false)]
public partial class InformationList {
    
    private InformationListInformation[] informationField;
    
    private string[] sourceNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Information")]
    public InformationListInformation[] Information {
        get {
            return this.informationField;
        }
        set {
            this.informationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SourceName")]
    public string[] SourceName {
        get {
            return this.sourceNameField;
        }
        set {
            this.sourceNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest")]
public partial class InformationListInformation {
    
    private int itemField;
    
    private ItemChoiceType itemElementNameField;
    
    private string[] synonymField;
    
    private int[] cIDField;
    
    private int[] sIDField;
    
    private int[] aIDField;
    
    private int[] giField;
    
    private int[] geneIDField;
    
    private DateTime depositionDateField;
    
    private DateTime modificationDateField;
    
    private DateTime creationDateField;
    
    private DateTime holdDateField;
    
    private string[] registryIDField;
    
    private string[] rnField;
    
    private int[] pubMedIDField;
    
    private int[] mMDBIDField;
    
    private string[] dBURLField;
    
    private string[] sBURLField;
    
    private int[] proteinGIField;
    
    private int[] nucleotideGIField;
    
    private int[] taxonomyIDField;
    
    private int[] mIMIDField;
    
    private int[] probeIDField;
    
    private string[] patentIDField;
    
    private string[] proteinNameField;
    
    private string[] geneSymbolField;
    
    private string[] sourceNameField;
    
    private string[] sourceCategoryField;
    
    private string titleField;
    
    private string descriptionField;
    
    private string descriptionSourceNameField;
    
    private string descriptionURLField;
    
    private string[] conformerIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AID", typeof(int), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("CID", typeof(int), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("SID", typeof(int), Order=0)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public int Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Synonym", Order=2)]
    public string[] Synonym {
        get {
            return this.synonymField;
        }
        set {
            this.synonymField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CID", Order=3)]
    public int[] CID {
        get {
            return this.cIDField;
        }
        set {
            this.cIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SID", Order=4)]
    public int[] SID {
        get {
            return this.sIDField;
        }
        set {
            this.sIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AID", Order=5)]
    public int[] AID {
        get {
            return this.aIDField;
        }
        set {
            this.aIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GI", Order=6)]
    public int[] GI {
        get {
            return this.giField;
        }
        set {
            this.giField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GeneID", Order=7)]
    public int[] GeneID {
        get {
            return this.geneIDField;
        }
        set {
            this.geneIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public DateTime DepositionDate {
        get {
            return this.depositionDateField;
        }
        set {
            this.depositionDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public DateTime ModificationDate {
        get {
            return this.modificationDateField;
        }
        set {
            this.modificationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public DateTime CreationDate {
        get {
            return this.creationDateField;
        }
        set {
            this.creationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public DateTime HoldDate {
        get {
            return this.holdDateField;
        }
        set {
            this.holdDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RegistryID", Order=12)]
    public string[] RegistryID {
        get {
            return this.registryIDField;
        }
        set {
            this.registryIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RN", Order=13)]
    public string[] RN {
        get {
            return this.rnField;
        }
        set {
            this.rnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PubMedID", Order=14)]
    public int[] PubMedID {
        get {
            return this.pubMedIDField;
        }
        set {
            this.pubMedIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MMDBID", Order=15)]
    public int[] MMDBID {
        get {
            return this.mMDBIDField;
        }
        set {
            this.mMDBIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DBURL", Order=16)]
    public string[] DBURL {
        get {
            return this.dBURLField;
        }
        set {
            this.dBURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SBURL", Order=17)]
    public string[] SBURL {
        get {
            return this.sBURLField;
        }
        set {
            this.sBURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ProteinGI", Order=18)]
    public int[] ProteinGI {
        get {
            return this.proteinGIField;
        }
        set {
            this.proteinGIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NucleotideGI", Order=19)]
    public int[] NucleotideGI {
        get {
            return this.nucleotideGIField;
        }
        set {
            this.nucleotideGIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TaxonomyID", Order=20)]
    public int[] TaxonomyID {
        get {
            return this.taxonomyIDField;
        }
        set {
            this.taxonomyIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MIMID", Order=21)]
    public int[] MIMID {
        get {
            return this.mIMIDField;
        }
        set {
            this.mIMIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ProbeID", Order=22)]
    public int[] ProbeID {
        get {
            return this.probeIDField;
        }
        set {
            this.probeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PatentID", Order=23)]
    public string[] PatentID {
        get {
            return this.patentIDField;
        }
        set {
            this.patentIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ProteinName", Order=24)]
    public string[] ProteinName {
        get {
            return this.proteinNameField;
        }
        set {
            this.proteinNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GeneSymbol", Order=25)]
    public string[] GeneSymbol {
        get {
            return this.geneSymbolField;
        }
        set {
            this.geneSymbolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SourceName", Order=26)]
    public string[] SourceName {
        get {
            return this.sourceNameField;
        }
        set {
            this.sourceNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SourceCategory", Order=27)]
    public string[] SourceCategory {
        get {
            return this.sourceCategoryField;
        }
        set {
            this.sourceCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=28)]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=29)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=30)]
    public string DescriptionSourceName {
        get {
            return this.descriptionSourceNameField;
        }
        set {
            this.descriptionSourceNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=31)]
    public string DescriptionURL {
        get {
            return this.descriptionURLField;
        }
        set {
            this.descriptionURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ConformerID", Order=32)]
    public string[] ConformerID {
        get {
            return this.conformerIDField;
        }
        set {
            this.conformerIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    AID,
    
    /// <remarks/>
    CID,
    
    /// <remarks/>
    SID,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest", IsNullable=false)]
public partial class IdentifierList {
    
    private int[] cIDField;
    
    private int[] sIDField;
    
    private int[] aIDField;
    
    private string listKeyField;
    
    private int sizeField;
    
    private bool sizeFieldSpecified;
    
    private string entrezDBField;
    
    private string entrezWebEnvField;
    
    private int entrezQueryKeyField;
    
    private bool entrezQueryKeyFieldSpecified;
    
    private string entrezURLField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CID")]
    public int[] CID {
        get {
            return this.cIDField;
        }
        set {
            this.cIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SID")]
    public int[] SID {
        get {
            return this.sIDField;
        }
        set {
            this.sIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AID")]
    public int[] AID {
        get {
            return this.aIDField;
        }
        set {
            this.aIDField = value;
        }
    }
    
    /// <remarks/>
    public string ListKey {
        get {
            return this.listKeyField;
        }
        set {
            this.listKeyField = value;
        }
    }
    
    /// <remarks/>
    public int Size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SizeSpecified {
        get {
            return this.sizeFieldSpecified;
        }
        set {
            this.sizeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string EntrezDB {
        get {
            return this.entrezDBField;
        }
        set {
            this.entrezDBField = value;
        }
    }
    
    /// <remarks/>
    public string EntrezWebEnv {
        get {
            return this.entrezWebEnvField;
        }
        set {
            this.entrezWebEnvField = value;
        }
    }
    
    /// <remarks/>
    public int EntrezQueryKey {
        get {
            return this.entrezQueryKeyField;
        }
        set {
            this.entrezQueryKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EntrezQueryKeySpecified {
        get {
            return this.entrezQueryKeyFieldSpecified;
        }
        set {
            this.entrezQueryKeyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string EntrezURL {
        get {
            return this.entrezURLField;
        }
        set {
            this.entrezURLField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest", IsNullable=false)]
public partial class Table {
    
    private string[] columnsField;
    
    private string[][] rowField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Column", IsNullable=false)]
    public string[] Columns {
        get {
            return this.columnsField;
        }
        set {
            this.columnsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Cell", typeof(string), IsNullable=false)]
    public string[][] Row {
        get {
            return this.rowField;
        }
        set {
            this.rowField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest", IsNullable=false)]
public partial class TableSummary {
    
    private int numberOfRowsField;
    
    private TableSummaryColumnValues[] columnValuesField;
    
    /// <remarks/>
    public int NumberOfRows {
        get {
            return this.numberOfRowsField;
        }
        set {
            this.numberOfRowsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ColumnValues")]
    public TableSummaryColumnValues[] ColumnValues {
        get {
            return this.columnValuesField;
        }
        set {
            this.columnValuesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest")]
public partial class TableSummaryColumnValues {
    
    private string columnNameField;
    
    private TableSummaryColumnValuesItem[] itemField;
    
    /// <remarks/>
    public string ColumnName {
        get {
            return this.columnNameField;
        }
        set {
            this.columnNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Item")]
    public TableSummaryColumnValuesItem[] Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest")]
public partial class TableSummaryColumnValuesItem {
    
    private string valueField;
    
    private int countField;
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public int Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest", IsNullable=false)]
public partial class AssaySummary {
    
    private int aIDField;
    
    private string sourceNameField;
    
    private string sourceIDField;
    
    private string nameField;
    
    private string[] descriptionField;
    
    private string[] protocolField;
    
    private string[] commentField;
    
    private int numberOfTIDsField;
    
    private bool hasScoreField;
    
    private string methodField;
    
    private AssaySummaryTarget[] targetField;
    
    private int versionField;
    
    private int revisionField;
    
    private DateTime lastDataChangeField;
    
    private int sIDCountAllField;
    
    private int sIDCountActiveField;
    
    private int sIDCountInactiveField;
    
    private int sIDCountInconclusiveField;
    
    private int sIDCountUnspecifiedField;
    
    private int sIDCountProbeField;
    
    private int cIDCountAllField;
    
    private int cIDCountActiveField;
    
    private int cIDCountInactiveField;
    
    private int cIDCountInconclusiveField;
    
    private int cIDCountUnspecifiedField;
    
    private int cIDCountProbeField;
    
    /// <remarks/>
    public int AID {
        get {
            return this.aIDField;
        }
        set {
            this.aIDField = value;
        }
    }
    
    /// <remarks/>
    public string SourceName {
        get {
            return this.sourceNameField;
        }
        set {
            this.sourceNameField = value;
        }
    }
    
    /// <remarks/>
    public string SourceID {
        get {
            return this.sourceIDField;
        }
        set {
            this.sourceIDField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description")]
    public string[] Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Protocol")]
    public string[] Protocol {
        get {
            return this.protocolField;
        }
        set {
            this.protocolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Comment")]
    public string[] Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    public int NumberOfTIDs {
        get {
            return this.numberOfTIDsField;
        }
        set {
            this.numberOfTIDsField = value;
        }
    }
    
    /// <remarks/>
    public bool HasScore {
        get {
            return this.hasScoreField;
        }
        set {
            this.hasScoreField = value;
        }
    }
    
    /// <remarks/>
    public string Method {
        get {
            return this.methodField;
        }
        set {
            this.methodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public AssaySummaryTarget[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    public int Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    public int Revision {
        get {
            return this.revisionField;
        }
        set {
            this.revisionField = value;
        }
    }
    
    /// <remarks/>
    public DateTime LastDataChange {
        get {
            return this.lastDataChangeField;
        }
        set {
            this.lastDataChangeField = value;
        }
    }
    
    /// <remarks/>
    public int SIDCountAll {
        get {
            return this.sIDCountAllField;
        }
        set {
            this.sIDCountAllField = value;
        }
    }
    
    /// <remarks/>
    public int SIDCountActive {
        get {
            return this.sIDCountActiveField;
        }
        set {
            this.sIDCountActiveField = value;
        }
    }
    
    /// <remarks/>
    public int SIDCountInactive {
        get {
            return this.sIDCountInactiveField;
        }
        set {
            this.sIDCountInactiveField = value;
        }
    }
    
    /// <remarks/>
    public int SIDCountInconclusive {
        get {
            return this.sIDCountInconclusiveField;
        }
        set {
            this.sIDCountInconclusiveField = value;
        }
    }
    
    /// <remarks/>
    public int SIDCountUnspecified {
        get {
            return this.sIDCountUnspecifiedField;
        }
        set {
            this.sIDCountUnspecifiedField = value;
        }
    }
    
    /// <remarks/>
    public int SIDCountProbe {
        get {
            return this.sIDCountProbeField;
        }
        set {
            this.sIDCountProbeField = value;
        }
    }
    
    /// <remarks/>
    public int CIDCountAll {
        get {
            return this.cIDCountAllField;
        }
        set {
            this.cIDCountAllField = value;
        }
    }
    
    /// <remarks/>
    public int CIDCountActive {
        get {
            return this.cIDCountActiveField;
        }
        set {
            this.cIDCountActiveField = value;
        }
    }
    
    /// <remarks/>
    public int CIDCountInactive {
        get {
            return this.cIDCountInactiveField;
        }
        set {
            this.cIDCountInactiveField = value;
        }
    }
    
    /// <remarks/>
    public int CIDCountInconclusive {
        get {
            return this.cIDCountInconclusiveField;
        }
        set {
            this.cIDCountInconclusiveField = value;
        }
    }
    
    /// <remarks/>
    public int CIDCountUnspecified {
        get {
            return this.cIDCountUnspecifiedField;
        }
        set {
            this.cIDCountUnspecifiedField = value;
        }
    }
    
    /// <remarks/>
    public int CIDCountProbe {
        get {
            return this.cIDCountProbeField;
        }
        set {
            this.cIDCountProbeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest")]
public partial class AssaySummaryTarget {
    
    private int giField;
    
    private string nameField;
    
    /// <remarks/>
    public int GI {
        get {
            return this.giField;
        }
        set {
            this.giField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/pug_rest", IsNullable=false)]
public partial class AssaySummaries {
    
    private AssaySummary[] assaySummaryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AssaySummary")]
    public AssaySummary[] AssaySummary {
        get {
            return this.assaySummaryField;
        }
        set {
            this.assaySummaryField = value;
        }
    }
}
